{{- if and .Values.token (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: blocklist-api
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "blocklist-api.labels" . | indent 4 }}
type: Opaque
stringData:
  BLOCKLIST_TOKEN: {{ .Values.token | quote }}
{{- end }}
